config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  resources :animals
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update]
  def index
    @animals = Animal.all
  end

  def show
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id]).destroy
    redirect_to animals_path
  end

  private

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.submit %>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit</h1>
<%= render 'animals/form'%>

app/views/animals/index.html.erb
<h1>People</h1>
<h4><%= link_to 'New Person', new_animal_path %></h4>
<% @animals.each do |animal| %>
  <h5> <%= animal.name %> </h5>
  <%= link_to 'Show', animal_path(animal) %>
  <%= link_to 'Edit', edit_animal_path(animal) %>
  <%= link_to 'Delete', animal, method: :delete %>
<%end%>

app/views/animals/new.html.erb
<h1>New Person</h1>
<%= render 'animals/form' %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>
<h4><%= "Age: #{@animal.age}" %></h4>
<h4><%= "Hair Color: #{@animal.hair_color}" %></h4>
<h4><%= "Eye Color: #{@animal.eye_color}" %></h4>
<h4><%= "Gender: #{@animal.gender }"%></h4>
<h4><%= "Alive: #{@animal.alive}" %></h4>

app/views/layouts/_navbar.html.erb
<div class="waves-effect black btn">
  <%= link_to 'Home', root_path %>  
</div>
  <div class="waves-effect black btn">
<%= link_to 'About', about_path %>
  </div>
<div class="waves-effect black btn">
  <%= link_to 'Animals', animals_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Person</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <%= render 'layouts/navbar' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About People</h1>
<p>They pretty cool and stuff</p>

app/views/static_pages/home.html.erb
<h1>People</h1>
<p>Database of People</p>